//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyanTour
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Express
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Express()
        {
            this.Express_Booking = new HashSet<Express_Booking>();
        }

        public HttpPostedFileBase File { get; set; }
        public string Id { get; set; }
        public string CarNo { get; set; }
        public string DriverName { get; set; }
        public string Model { get; set; }
        public byte[] Pic { get; set; }
        public string Seat { get; set; }
        public string AvailableSeat { get; set; }
        public string State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Express_Booking> Express_Booking { get; set; }
    }
}
