//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MyanTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Express_Booking
    {
        public string Id { get; set; }
        public string CustomerID { get; set; }
        public string VehicalID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EndDate { get; set; }
        public string FerryPoint { get; set; }
        public string Loc { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public string State { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Express Express { get; set; }
    }
}
