//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyanTour
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Flight_Booking = new HashSet<Flight_Booking>();
        }
        public HttpPostedFileBase File { get; set; }
        public string Id { get; set; }
        public string flightCode { get; set; }
        public string Pilot { get; set; }
        public string Model { get; set; }
        public byte[] Pic { get; set; }
        public string Seat { get; set; }
        public string AvailableSeat { get; set; }
        public string State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Booking> Flight_Booking { get; set; }
    }
}
